openapi: 3.0.3
info:
  title: AutoFlow API Documentation
  description: API documentation for AutoFlow platform
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@autoflow.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:5432
    description: Development server
tags:
  - name: Pipelines
    description: Pipeline management endpoints
paths:
  /api/v1/pipeline:
    post:
      summary: Create a new pipeline
      tags:
        - Pipelines
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                published:
                  type: boolean
                metadata:
                  type: object
      responses:
        '201':
          description: Pipeline created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  statusCode:
                    type: number
                    example: 201
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
        '409':
          description: Conflicting pipeline name
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Pipeline with the same name already exists
                  errors:
                    type: object
                    properties:
                      code:
                        type: string
                        example: SQLITE_CONSTRAINT_UNIQUE
    get:
      summary: Fetch all pipelines
      tags:
        - Pipelines
      responses:
        '200':
          description: Pipelines fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pipeline'
  /api/v1/pipeline/{id}:
    get:
      summary: Fetch a single pipeline
      tags:
        - Pipelines
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Pipeline ID
      responses:
        '200':
          description: Pipeline fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
    put:
      summary: Update a pipeline
      tags:
        - Pipelines
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Pipeline ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                metadata:
                  type: object
      responses:
        '200':
          description: Pipeline updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
    delete:
      summary: Delete a pipeline
      tags:
        - Pipelines
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Pipeline ID
      responses:
        '200':
          description: Pipeline deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
  /api/v1/pipeline/{id}/clone:
    get:
      summary: Clone a pipeline
      tags:
        - Pipelines
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Pipeline ID
      responses:
        '200':
          description: Pipeline cloned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
  /api/v1/pipeline/{id}/run:
    get:
      summary: Execute a pipeline
      tags:
        - Pipelines
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Pipeline ID
      responses:
        '200':
          description: Pipeline execution started
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Pipeline'
components:
  schemas:
    Pipeline:
      type: object
      required:
        - id
        - name
        - userId
      properties:
        id:
          type: string
          description: Pipeline unique identifier
        name:
          type: string
          description: Pipeline name
        description:
          type: string
          description: Pipeline description
        userId:
          type: string
          description: Owner of the pipeline
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
        errors:
          type: object
